### PR TITLE
update

### PR DESCRIPTION
**Pull request by first3234**
fixed some team numbers in the matches

### CODE REVIEW

**Comment by chacha** [comment]
I checked the first match, and currently for `2015wmri_qf1m6` it listed `frc86` as the competitor. Because of that, this fix needs to be applied at the TBA database level first and then it will filter down from there. 

Fixing it directly in this data dump won't fix the website, API, or any other dataset. Plus it will get overwritten the next time it is exported.

**Comment by first3234** [comment]
yea its is realy team 85 i forgot to change it before uploading it th reson why i put 86 insted of 85 is becuse when we were encrypting routers 85s encryption was not working so we used 86 instead

**Comment by synth3tk** [comment]
This repo is actually just a data dump from the website, this pull request won't actually fix it. Opened an issue at the-blue-alliance/the-blue-alliance#1319.

**Comment by fangeugene** [comment]
Done.

**Pull request closed without merging**
